plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 10

RSpec/DescribedClass:
  Enabled: false